services:
  camdetect:
    build: .
    container_name: camdetect
    restart: unless-stopped

    devices:
      - "/dev/video0:/dev/video0"

    environment:
      - CAMERA_INDEX=0
      - SCORE_THRESH=0.55
      - COOLDOWN_SEC=10
      - ALERT_MODE=arduino_cloud
      - ARDUINO_DEVICE_ID=<deviceID> 
      - ARDUINO_SECRET_KEY=<secretKey>

      - VAR_PERSON=person_detected
      - VAR_DOG=dog_detected
      - VAR_LAST_LABEL=last_label
      - VAR_LAST_SCORE=last_score
      - VAR_LAST_TS=last_ts
